dbt_project:
 target: dev
 outputs:
  dev:
    type: bigquery
    method: service-account
    keyfile: /usr/local/airflow/include/gcp/service_account.json
    project: data-435516
    dataset: Mobile
    threads: 1
    timeout_seconds: 300
    location: US